task:
  name: classification_large
  output_dir_name: classification_large
  batch_size: 512
  max_epochs: 80
  max_steps: 50_080
  target_metric: val_top5_err
  target_metric_mode: min
  # model: davit_tiny
  model:
    name: wide_resnet50_2
    hidden_channel: 300  # TODO
    kernel_size: 3
    padding: 1
    maxpool: True
  train_transforms:
    random_crop:
      use: True
      size: 64
      padding: 4
      padding_mode: reflect
    horizontal_flip:
      use: True
      p: 0.5
    trivial_augment:
      use: True
engine:
  devices: 4
