workload:
  name: segmentation
  output_dir_name: segmentation
  batch_size: 16
  max_epochs: 32
  max_steps: 10_112
  target_metric: val_mean_accuracy
  target_metric_mode: max
engine:
  devices: 4
optimizer:
  learning_rate: 6.e-5
