workload:
  name: template
  output_dir_name: template
  batch_size: 10
  max_epochs: 15
  max_steps: 150
  target_metric: val_loss  # choose a metric that is being logged
  target_metric_mode: min  # min or max 
  dataset_split_lengths: [80, 10, 10]
  model:  # small MLP (name of model as comment might be a good idea)
    hidden_channels: 10
    activation: relu  # this parameter has to be in {relu, gelu}, modify the model.py to support more
runtime:
  devices: 1
submission:  # you can set your favourite baseline as default like this
  name: adamw_baseline
  lr: 1.e-3  # you can also set a good default for the hyperparameter
