workload:
  - name: mnist
    model:
      num_layers: 3
      activation: GELU
  - name: cifar100
    batch_size: [64, 128, 256]
submission:
  name: adamw_baseline
  lr: 1.e-3
  weight_decay: [1.0, 1.e-1, 1.e-2, 1.e-3, 1.e-4]
