task:
  name: mnist
  max_steps: 2000
  model:
    num_hidden: 256
optimizer:
  - name: adam
    learning_rate: [1.0e-4, 5.0e-4, 1.0e-3, 5.0e-3, 1.0e-2, 2.0e-2]
    weight_decay: 0.0
    lr_scheduler:
      scheduler: identity
      warmup_factor: 0.0
  - name: flora
    rank: 16
    learning_rate: [1.0e-4, 5.0e-4, 1.0e-3, 5.0e-3, 1.0e-2, 2.0e-2]
    kappa: 100
    lr_scheduler:
      scheduler: identity
    weight_decay: 0.0
    warmup_factor: 0.0
  # - name: floraAF
  # - name: floraDR
engine:
  seed: [42, 123, 888]
  plot: true
