task:
  name: mnist
  max_steps: 2000
  model:
    num_hidden: 256
optimizer:
  - name: flora
    rank: [2, 4, 8, 16, 32, 64]
    learning_rate: 5.0e-3
    kappa: 100
    learning_rate_scheduler:
      scheduler: identity
  # - name: floraAF
  # - name: floraDR
engine:
  seed: [42, 123, 888]
  plot: true
