workload:
  name: cifar100
  output_dir_name: cifar100
  batch_size: 128
  max_epochs: 50
  max_steps: 19_550
  model: resnet18
  target_metric: val_acc
  target_metric_mode: max
runtime:
  devices: 1
