task:
  name: mnist
optimizer:
  name: adamw_baseline
  learning_rate: [1.0e-2, 1.0e-3]
  weight_decay: [0.1, 0.01]
engine:
  data_dir: ./evaluation/example/data
  output_dir: ./evaluation/example/experiments
  seed: [1, 2, 3]
  silent: True
  workers: 2

