task:
  name: mnist
optimizer:
  name: sgd_baseline
  learning_rate: [0.01, 0.001]
  weight_decay: [1.e-4, 1.e-5]
engine:
  data_dir: ./evaluation/example/data
  output_dir: ./evaluation/example/experiments
  seed: [1, 2, 3]
  silent: True
  workers: 2
