optimizer:
  name: sgd_baseline
  output_dir_name: sgd_baseline
  learning_rate: 1.e-2  # SGD parameter
  momentum: 0.9         # SGD parameter
  weight_decay: 1.e-4   # SGD parameter
  eta_min_factor: 0.01  # the minimum learning rate of the cosine annealing given as a factor of the initial learning rate
  nesterov: false       # enables Nesterov momentum for SGD
  lr_interval: step     # epoch is possible but step is preferred
