workload:
  name: tabular
  output_dir_name: tabular
  train_split: 0.8
  batch_size: 256
  max_epochs: 100
  max_steps: 5_120  # 25600 was roughly 492, so i divided that by 5 to get the 100 epochs... close enough for now
  target_metric: val_loss
  target_metric_mode: min
  model:  # FTTransformer
    n_blocks: 3  # The supported values are: 1, 2, 3, 4, 5, 6
runtime:
  devices: 1
