task:
  name: graph_tiny
  max_epochs: 200
  model:  # GCN
    hidden_channels: 16
    reset_params: true
optimizer:
  name: adamw_baseline
  learning_rate: 1.0e-1
  weight_decay: 0
  eta_min_factor: 0
engine:
  early_stopping: 10
