workload:
  name: coco
  output_dir_name: coco
  batch_size: 8
  max_epochs: 26
  max_steps: 381_134
  target_metric: val_AP
  target_metric_mode: max
  model: fasterrcnn_mobilenet_v3_large_fpn
  train_transforms:
    random_horizontal_flip: 0.5

runtime:
  devices: 4
