workload:
  name: ogbg
  output_dir_name: ogbg
  batch_size: 32
  target_metric: val_rocauc
  target_metric_mode: max
  max_epochs: 50
  max_steps: 51_600
  # GIN
  model:
    hidden_channels: 300
    num_layers: 5
    dropout: 0.5
    jumping_knowledge: last
runtime:
  devices: 1