optimizer:
  name: adam  # same as folder name
  learning_rate: 1.e-3  # AdamW parameter 
  beta1: 0.9            # AdamW parameter
  beta2: 0.999          # AdamW parameter
  eps: 1.e-8        # AdamW parameter